### ISSUE TITLE
请问可以提供DotNet的SDK吗？

### ISSUE THREAD

**Issue by bebestmaple** [tuputech/tupu-dotnet-sdk#1]
请问可以提供DotNet的SDK吗？

**Comment by nickeljew** [comment]
抱歉，我们没有.Net 技术栈。你可以参考一下其他语言来实现。
- 只是一个常规的 form 表单提交的，大部分语言都有现成的库可以使用（除了 PHP 需要手工撸数据结构）；
- 返回值需要两重 JSON 解析，第一重解出签名和数据内容的字符串，用前者来校验后者合法性（如果不考虑安全问题也可以忽略这一步）；第二重就是把上一步的后者再次解析 JSON 数据得到识别结果。

**Comment by bebestmaple** [comment]
我有尝试自己参照其它语言的实现，但加密解密那边有点问题不能打通

**Comment by nickeljew** [comment]
没有加密解密，是签名和验证签名。首先你代码自己能验证自己代码生成的签名，其次要保证被签名的串和算法和我们要求的一致，

**Comment by bebestmaple** [comment]
对的 就是签名这里打不通
